"""
Simple single-file URL shortener using Flask + SQLite
Features:
- Short codes generated by Base62-encoding the row id (guaranteed unique)
- Supports optional custom alias (if not taken)
- Web UI to shorten URLs and to view basic stats
- JSON API: POST /api/shorten {"url": "...", "custom_alias": "..."}

How to run:
1. Create & activate a virtualenv (recommended):
   python -m venv venv
   source venv/bin/activate   # on Windows: venv\Scripts\activate
2. Install dependencies:
   pip install Flask validators
3. Run:
   python flask_url_shortener.py
4. Open http://127.0.0.1:5000/ in your browser.

Note: This is a small demo. For production, add authentication, input rate limits,
secure headers, HTTPS, and better error handling.
"""

from flask import Flask, request, redirect, jsonify, render_template_string, abort
import sqlite3
from datetime import datetime
import validators
import os
import threading

DB_PATH = os.path.join(os.path.dirname(__file__), 'urls.db')
BASE62_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

app = Flask(__name__)
lock = threading.Lock()

# ---------------------
# Database helpers
# ---------------------

def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    with get_db() as db:
        db.execute('''
            CREATE TABLE IF NOT EXISTS urls (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                original TEXT NOT NULL,
                code TEXT UNIQUE,
                custom_alias INTEGER DEFAULT 0,
                created_at TEXT NOT NULL,
                visits INTEGER DEFAULT 0,
                last_access TEXT
            )
        ''')
        db.commit()

# ---------------------
# Base62 encode/decode (for short codes)
# ---------------------

def encode_base62(num: int) -> str:
    if num == 0:
        return BASE62_ALPHABET[0]
    arr = []
    base = len(BASE62_ALPHABET)
    while num:
        num, rem = divmod(num, base)
        arr.append(BASE62_ALPHABET[rem])
    arr.reverse()
    return ''.join(arr)


def is_valid_custom_alias(alias: str) -> bool:
    # only allow base62 chars and length check
    if not alias:
        return False
    if len(alias) > 64:
        return False
    for ch in alias:
        if ch not in BASE62_ALPHABET:
            return False
    return True

# ---------------------
# Core logic
# ---------------------

def create_short_url(original_url: str, custom_alias: str = None) -> dict:
    if not validators.url(original_url):
        raise ValueError('Invalid URL')

    with lock:  # simple thread-safety for sqlite
        db = get_db()
        cur = db.cursor()

        # handle custom alias
        if custom_alias:
            if not is_valid_custom_alias(custom_alias):
                raise ValueError('Invalid custom alias — use [0-9a-zA-Z], max 64 chars')
            # check uniqueness
            cur.execute('SELECT * FROM urls WHERE code = ?', (custom_alias,))
            if cur.fetchone():
                raise ValueError('Alias already taken')
            now = datetime.utcnow().isoformat()
            cur.execute(
                'INSERT INTO urls (original, code, custom_alias, created_at) VALUES (?, ?, 1, ?)',
                (original_url, custom_alias, now)
            )
            db.commit()
            return {'code': custom_alias, 'original': original_url}

        # otherwise insert then encode id -> code
        now = datetime.utcnow().isoformat()
        cur.execute('INSERT INTO urls (original, created_at) VALUES (?, ?)', (original_url, now))
        rowid = cur.lastrowid
        code = encode_base62(rowid)
        cur.execute('UPDATE urls SET code = ? WHERE id = ?', (code, rowid))
        db.commit()
        return {'code': code, 'original': original_url}

# ---------------------
# Flask routes
# ---------------------

INDEX_HTML = """
<!doctype html>
<title>Mini URL Shortener</title>
<h1>Mini URL Shortener</h1>
<form method="post" action="/shorten">
  <input name="url" placeholder="https://example.com/very/long" size=60 required>
  <input name="custom_alias" placeholder="optional custom alias (a-zA-Z0-9)">
  <button type="submit">Shorten</button>
</form>
{% if short %}
<p>Short URL: <a href="{{ short }}">{{ short }}</a></p>
<p>Stats: <a href="/stats/{{ code }}">/stats/{{ code }}</a></p>
{% endif %}
<hr>
<h3>How to use the JSON API</h3>
<pre>
POST /api/shorten
Body: {"url": "https://...", "custom_alias": "optalias"}
Response: {"short_url": "http://.../<code>", "code": "<code>"}
</pre>
"""


@app.route('/')
def index():
    host = request.host_url.rstrip('/')
    code = request.args.get('c')
    short = None
    if code:
        short = f"{host}/{code}"
    return render_template_string(INDEX_HTML, short=short, code=code)


@app.route('/shorten', methods=['POST'])
def shorten_form():
    url = request.form.get('url')
    custom = request.form.get('custom_alias') or None
    try:
        result = create_short_url(url, custom_alias=custom)
    except ValueError as e:
        return f"Error: {e}", 400

    host = request.host_url.rstrip('/')
    short = f"{host}/{result['code']}"
    return render_template_string(INDEX_HTML, short=short, code=result['code'])


@app.route('/api/shorten', methods=['POST'])
def api_shorten():
    data = request.get_json(force=True, silent=True)
    if not data or 'url' not in data:
        return jsonify({'error': 'missing url field'}), 400
    url = data['url']
    custom = data.get('custom_alias')
    try:
        result = create_short_url(url, custom_alias=custom)
    except ValueError as e:
        return jsonify({'error': str(e)}), 400

    short_url = request.host_url.rstrip('/') + '/' + result['code']
    return jsonify({'short_url': short_url, 'code': result['code']})


@app.route('/<code>')
def redirect_short(code):
    db = get_db()
    cur = db.cursor()
    cur.execute('SELECT * FROM urls WHERE code = ?', (code,))
    row = cur.fetchone()
    if not row:
        abort(404)

    # update visits and last_access
    now = datetime.utcnow().isoformat()
    cur.execute('UPDATE urls SET visits = visits + 1, last_access = ? WHERE id = ?', (now, row['id']))
    db.commit()
    return redirect(row['original'])


STATS_HTML = """
<!doctype html>
<title>URL Stats: {{ code }}</title>
<h1>Stats for {{ code }}</h1>
<ul>
  <li>Original URL: <a href="{{ original }}">{{ original }}</a></li>
  <li>Created at: {{ created_at }}</li>
  <li>Visits: {{ visits }}</li>
  <li>Last access (UTC): {{ last_access }}</li>
</ul>
<a href="/">Back</a>
"""


@app.route('/stats/<code>')
def stats(code):
    db = get_db()
    cur = db.cursor()
    cur.execute('SELECT * FROM urls WHERE code = ?', (code,))
    row = cur.fetchone()
    if not row:
        abort(404)
    return render_template_string(STATS_HTML,
                                  code=code,
                                  original=row['original'],
                                  created_at=row['created_at'],
                                  visits=row['visits'],
                                  last_access=row['last_access'])

# ---------------------
# CLI support and startup
# ---------------------

if __name__ == '__main__':
    init_db()
    print('Starting Flask URL shortener...')
    app.run(debug=True)
